package com.fatimaezzahrakld.clientmanagement.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA Entity representing a client in the system.
 *
 * <p>
 * This class defines the data model for storing client-related information.
 * Instances of this class are persisted in the {@code clients} table of the
 * MySQL database.
 * </p>
 *
 * @author Kelladi fatimaezzahra
 * @version 1.0.0
 * @since 2025-12-29
 */
@Entity
@Table(name = "clients")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ClientEntity {

    /**
     * Unique technical identifier for the client.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "client_id")
    private Long clientIdentifier;

    /**
     * Full name of the client.
     * Includes both first and last names.
     */
    @Column(name = "complete_name", nullable = false)
    private String completeName;

    /**
     * Age of the client in years.
     * Represented as a float for potential precision.
     */
    @Column(name = "client_age")
    private Float clientAge;
}
